# Generated by Django 6.0.5 on 2026-06-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aicareer', '0003_result_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='metadata',
            field=models.JSONField(default=dict),
        ),
    ]
