# Generated by Django 6.0.1 on 2026-06-19 09:54

import aicareer.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aicareer', '0004_alter_repository_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_token',
            field=aicareer.models.EncryptedField(blank=True, default=''),
        ),
    ]
